### ISSUE TITLE
Retrieve env vars

### ISSUE THREAD

**Issue by gdude2002** [virtualdogbert/logback-groovy-config#4]
I can't figure out what the correct way to retrieve environmental variables is. If I do this the normal way:

```groovy
def environment = System.getenv().getOrDefault("ENVIRONMENT", "prod")
def logUrl = System.getenv().getOrDefault("DISCORD_LOGGER_URL", null)
```

...then I get the following...

```
java.lang.SecurityException: Expression [MethodCallExpression] is not allowed: java.lang.System.getenv().getOrDefault(ENVIRONMENT, prod)
	at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.assertExpressionAuthorized(SecureASTCustomizer.java:1045)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
...

at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:114)
at ch.qos.logback.classic.gaffer.GafferConfigurator$run.call(Unknown Source)
at ch.qos.logback.classic.LogbackDSLInitializer.init(LogbackDSLInitializer.groovy:26)
...
```

---

I have attempted to configure (via `logbackCompiler.groovy`) the security settings to allow for this, but it seems to only support imports, and doesn't have any configuration for expression types.

Any ideas?

**Comment by virtualdogbert** [comment]
`def environment = System.getenv("ENVIRONMENT") ?: "prod"
`
Should work as a stand-in for now. I have to look at this a little bit closer at the ScriptExpressionChecker and decided how I want to handle that. I have some ideas after debugging a little.

**Comment by virtualdogbert** [comment]
Also what version of the library are you using?

**Comment by gdude2002** [comment]
Oh, whoops, I forgot to include that. I'm using `1.14.0`, with logback `1.4.5`.

Either way, that's solved it - I guess I misread the javadoc for that method, thinking it would throw if the result was `null`. Thanks!
